name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5a9e4e28981a3829c54
        with:
          scandir: ./src

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bats-core/bats-action@2c88fe0acb1a9b4f2042c029c89185c65c8d3201
      - run: bats tests/
