name: 'Continuous Deployment'

on:
  workflow_dispatch:
    inputs:
      semantic:
        description: The SEMVER specification.
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || github.token }}
      - run: git pull --rebase origin main
      - uses: heronlabs/action-tag-release-build@v5.0.11
        id: version
        with:
          gh_token: ${{ secrets.RELEASE_PLEASE_TOKEN || github.token }}
          semantic: ${{ inputs.semantic }}
